version: '3.8'

services:
  opensis-web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/opensis
      - ./docker/php.ini:/etc/php5/apache2/php.ini
    depends_on:
      - opensis-db
    networks:
      - opensis-network
    environment:
      - DB_HOST=opensis-db
      - DB_PORT=3306
      - DB_NAME=opensis
      - DB_USER=opensis_user
      - DB_PASSWORD=opensis_pass

  opensis-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: opensis
      MYSQL_USER: opensis_user
      MYSQL_PASSWORD: opensis_pass
    ports:
      - "3306:3306"
    volumes:
      - opensis_db_data:/var/lib/mysql
      - ./install/OpensisSchemaMysqlInc.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./install/OpensisProcsMysqlInc.sql:/docker-entrypoint-initdb.d/02-procedures.sql
      - ./install/OpensisTriggerMysqlInc.sql:/docker-entrypoint-initdb.d/03-triggers.sql
      - ./install/SqlSampleDataInc.sql:/docker-entrypoint-initdb.d/04-sample-data.sql
    networks:
      - opensis-network
    command: --sql-mode=""

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - "8081:80"
    environment:
      PMA_HOST: opensis-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - opensis-db
    networks:
      - opensis-network

volumes:
  opensis_db_data:

networks:
  opensis-network:
    driver: bridge
